services:
  - type: web
    name: ai-interviewer-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          name: ai-interviewer-client
          type: web
          property: url
      - key: LEMONFOX_KEY
        sync: false
      - key: OPENAI_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/problems
    autoDeploy: true

  - type: web
    name: ai-interviewer-client
    env: static
    buildCommand: cd client && rm -rf node_modules package-lock.json && npm cache clean --force && npm install && npm install vite @vitejs/plugin-react --save-dev && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://ai-interviewer-server.onrender.com/api/:splat
      - type: rewrite
        source: /leetcode/*
        destination: https://ai-interviewer-server.onrender.com/leetcode/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true 